# Generated by Django 4.0.10 on 2023-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friendrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
